# Generated by Django 5.0.4 on 2024-05-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
