# Generated by Django 5.0.4 on 2024-05-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_thought_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='thought',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
